# Generated by Django 6.1.1 on 2026-09-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_rename_descreption_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('summary', 'Summary'), ('similar_books', 'Similar Books'), ('auto_tags', 'Auto Tags')], max_length=20)),
                ('result', models.TextField()),
                ('provider_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content', to='catalog.book')),
            ],
            options={
                'unique_together': {('book', 'type')},
            },
        ),
    ]
